---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0  

include:
  - project: 'test/essentials/ci'
    ref: main
    file: 'poppy/poppy.yml'

stages: 
  - poppy


# stages:
#   - poppy-generate
#   - poppy-upload


# test:
#   tags: ['alse']
#   stage: poppy-generate
#   script:
#     - pwd
#     - echo $CI_PROJECT_PATH
#     - echo $CI_PROJECT_DIR

# include:
#   - project: 'test/essentials/ci'
#     ref: main
#     file: 
#       - 'poppy/any-src-artifacts.yml'
#       - 'poppy/upload-artifactory.yml'
    
