---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0  

include:
  - project: 'test/essentials/ci'
    ref: main
    file: 'poppy/poppy.yml'

stages: 
  - build
  - poppy
    
