---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0  

stages:
  - poppy-generate
  - poppy-upload

include:
  - project: 'test/essentials/ci'
    ref: main
    file: 'poppy/any-src-artifacts.yml'

  - project: 'test/essentials/ci'
    ref: main
    file: 'poppy/upload-artifactory.yml'

