macro(project_version_patch_clean)
  message(STATUS "[${PROJECT_NAME}] cleaning version...")
  if(NOT PROJECT_VERSION_PATCH)
    set(PROJECT_VERSION_PATCH 0)
  endif()

  if(NOT PROJECT_VERSION_TWEAK)
    set(PROJECT_VERSION_TWEAK 0)
  endif()
endmacro()

macro(qt_os_bundle_setup)
  message(STATUS "[${PROJECT_NAME}] configuring os bundle...")
  if(APPLE)
    set(OS_BUNDLE MACOSX_BUNDLE)
  elseif(WIN32)
    set(OS_BUNDLE WIN32)
  endif()
endmacro()

macro(generate_meta_files __OUTPUT_SET __ICON_FILE __RC_FILE)
  project_version_patch_clean()
  qt_os_bundle_setup()

  message(STATUS "[${PROJECT_NAME}] generating meta files...")

  if(WIN32)
    set(ICON_FILE ${__ICON_FILE})
    configure_file(${__RC_FILE} "windows_metafile.rc")
    set(RES_FILES "windows_metafile.rc")
    set(CMAKE_RC_COMPILER_INIT windres)
    enable_language(RC)
    set(CMAKE_RC_COMPILE_OBJECT "<CMAKE_RC_COMPILER> <FLAGS> -O coff <DEFINES> -i <SOURCE> -o <OBJECT>")
    set(${__OUTPUT_SET} ${RES_FILES})
  endif()
endmacro()
