# Links static libgcc and libstdc++ on Windows
# Usage: enable_static_crt()
macro(enable_static_crt)
  if(WIN32)
    if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
      message(STATUS "[${PROJECT_NAME}] using msvc compiler, static libgcc and libstdc++ skipped")
    else()
      target_link_options(${PROJECT_NAME} PRIVATE -static-libgcc -static-libstdc++)
      message(STATUS "[${PROJECT_NAME}] static libgcc and libstdc++ enabled")
    endif()
  else()
    message(STATUS "[${PROJECT_NAME}] skipping static libgcc and libstdc++, target platform is not windows")
  endif()
endmacro()